### ISSUE TITLE
Exact order of orders in the order book can not always be recovered from Bitfinex data, or can it?

### ISSUE THREAD

**Issue by petr-fedorov** [petr-fedorov/obadiah#11]
Below are few trades with the same price (apart from the last one) from Bitfinex in descending order (latest trades first). Note the three at the bottom - event_no in the wrong order:
![2018-07-24 21-15-12](https://user-images.githubusercontent.com/949629/43157831-c75f313e-8f86-11e8-83c2-26002f0f64ac.png) 

Here are the first twenty events for the episode 67990:

![2018-07-24 21-35-51](https://user-images.githubusercontent.com/949629/43158930-ab11b094-8f89-11e8-9d27-3fa199cddd92.png)

The second trade (qty: 0.00491516)  from the bottom  is matched to the order 14700181411 (event_no 9, highlighted above). All order book events related to the order are show below:

![2018-07-24 21-20-49](https://user-images.githubusercontent.com/949629/43158093-7b4acc9e-8f87-11e8-80d7-141f2d039c7c.png)

And the thrid trade (qty: 0.00480257) has been matched to the order 14700180511 (event_no 7) :
![2018-07-24 21-18-30](https://user-images.githubusercontent.com/949629/43158018-4444f7b0-8f87-11e8-8302-4b2f0105cebd.png)

It is clear that trade 3's order 14700180511  has been placed before trade 2's 14700181411 (judging by their numbers and also by exchange_timestamps of their first events:   2018-07-24 20:51:55.705+03 vs 2018-07-24 20:51:56.081+03).

Both orders entered the price level 8232 at exactly the same time: 2018-07-24 20:52:07.343+03, 
but still trade 2 happened before trade 3. Why?   Due to slightly bigger  amount?

**Comment by FrancoBenner** [comment]
hey, are you on discord?

**Comment by petr-fedorov** [comment]
It has been resolved actually - forgot to close
